package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseComment<M extends BaseComment<M>> extends Model<M> implements IBean {

	public void setCdid(java.lang.Integer cdid) {
		set("cdid", cdid);
	}

	public java.lang.Integer getCdid() {
		return get("cdid");
	}

	public void setCuid(java.lang.Integer cuid) {
		set("cuid", cuid);
	}

	public java.lang.Integer getCuid() {
		return get("cuid");
	}

	public void setComment(java.lang.String comment) {
		set("comment", comment);
	}

	public java.lang.String getComment() {
		return get("comment");
	}

}
