package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDraw<M extends BaseDraw<M>> extends Model<M> implements IBean {

	public void setDid(java.lang.Integer did) {
		set("did", did);
	}

	public java.lang.Integer getDid() {
		return get("did");
	}

	public void setDlike(java.lang.Integer dlike) {
		set("dlike", dlike);
	}

	public java.lang.Integer getDlike() {
		return get("dlike");
	}

	public void setDurl(java.lang.String durl) {
		set("durl", durl);
	}

	public java.lang.String getDurl() {
		return get("durl");
	}

	public void setUdid(java.lang.Integer udid) {
		set("udid", udid);
	}

	public java.lang.Integer getUdid() {
		return get("udid");
	}

}
