package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}

	public java.lang.Integer getUid() {
		return get("uid");
	}

	public void setUpwd(java.lang.String upwd) {
		set("upwd", upwd);
	}

	public java.lang.String getUpwd() {
		return get("upwd");
	}

	public void setUname(java.lang.String uname) {
		set("uname", uname);
	}

	public java.lang.String getUname() {
		return get("uname");
	}

	public void setUaccount(java.lang.String uaccount) {
		set("uaccount", uaccount);
	}

	public java.lang.String getUaccount() {
		return get("uaccount");
	}

	public void setUimage(java.lang.String uimage) {
		set("uimage", uimage);
	}

	public java.lang.String getUimage() {
		return get("uimage");
	}

}
