package com.demo.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		// Composite Primary Key order: cdid,cuid
		arp.addMapping("comment", "cdid,cuid", Comment.class);
		arp.addMapping("draw", "did", Draw.class);
		arp.addMapping("request", "rid", Request.class);
		arp.addMapping("user", "uid", User.class);
	}
}

