package com.demo.common.model;

import com.demo.common.model.base.BaseComment;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Comment extends BaseComment<Comment> {
	public static final Comment me = new Comment();
	
	public Page<Comment> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from comment order by cdid asc");
	}
}
