package com.demo.common.model;

import com.demo.common.model.base.BaseDraw;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Draw extends BaseDraw<Draw> {
	public static final Draw me = new Draw();
	
	public Page<Draw> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from draw order by did asc");
	}
}
