package com.demo.common.model;

import com.demo.common.model.base.BaseRequest;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Request extends BaseRequest<Request> {
	public static final Request me = new Request();
	
	public Page<Request> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from request order by rid asc");
	}
}
